import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  TextField,
  InputAdornment,
  FormControl,
  CardMedia,
  Button,
  styled,
  Box,
  Card,
} from "@mui/material";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Logo from "../components/Logo";
import Link from "next/link";

const theme = createTheme({
  palette: {
    primary: {
      main: "#706E69",
    },
    secondary: {
      main: "#1D99BE",
    },
  },
});

export default function Home() {
  const phoneLabel = <span className={styles.black}>Phone*</span>;
  const label = <span className={styles.black}>Zipcode*</span>;
  const zipLabel = `Zipcode ${label}`;

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Herewith</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/herewithfavicon.png" />
      </Head>
      <div className={styles.logoContainer}>
        <Logo />
      </div>
      <Card className={styles.card}>
        <div className={styles.headerContainer}>
          <CardMedia
            component="img"
            height="286"
            image="/assets/headerimage-welcome-xs.png"
            alt="Welcome"
            className={styles.headerxs}
          />
          <CardMedia
            component="img"
            height="286"
            image="/assets/headerimage-welcome-sm.png"
            alt="Welcome"
            className={styles.headersm}
          />
        </div>

        <main className={styles.main}>
          <h1 className={styles.title}>Ready to find care?</h1>

          <p className={styles.description}>
            We’ll use your zip code to check for caregivers in your area, then
            customize the list based on your care needs and preferences.
          </p>
          <FormControl fullWidth sx={{ m: 1 }}>
            <TextField
              margin="normal"
              id="phone-number"
              label={phoneLabel}
              type="search"
              variant="outlined"
              InputProps={{
                endAdornment: (
                  <InputAdornment position="end">Phone Number</InputAdornment>
                ),
              }}
            />
            <TextField
              margin="normal"
              id="zipcode"
              // label='zipcode'
              label={label}
              type="search"
              variant="outlined"
              InputProps={{
                endAdornment: (
                  <InputAdornment position="end">e.g. 94102</InputAdornment>
                ),
              }}
            />
          </FormControl>
          <div className={styles.reminder}>
            <div className={styles.red}>*</div> Required to complete your
            profile
          </div>
        </main>
      </Card>

      <Box className={styles.btnBox}>
        <Button className={styles.backBtn} fullWidth>
          back
        </Button>
        <Link href={'/When'}>
        <Button className={styles.nextBtn} fullWidth>
          Next
        </Button>
        </Link>

      </Box>
    </ThemeProvider>
  );
}
